# Generated by Django 5.1.1 on 2024-10-14 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medikua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pazientea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zitak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordua', models.DateTimeField(default=django.utils.timezone.now)),
                ('mediku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medikua.medikua')),
                ('pazientea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medikua.pazientea')),
            ],
        ),
    ]
